import type { Drill } from "./drill-library";

export const agilityDrills: Drill[] = [
  {
    name: "Split-Step Path",
    level: "foundation",
    purpose: "Move early and arrive balanced instead of hitting while running.",
    setup: "Place markers at the baseline, transition zone, and kitchen line.",
    steps: [
      "Move from one marker to the next using short, controlled steps.",
      "Split-step at every marker and hold a balanced ready position.",
      "Keep your chest forward and avoid crossing your feet.",
    ],
    socialTarget: "Complete 6 smooth paths with full balance at each marker.",
    competitiveTarget: "Complete 8 paths while reacting to random left-or-right calls.",
    solo: "Use three markers and change direction after every split-step.",
    partner: "A partner points left or right as you arrive at each marker.",
  },
  {
    name: "Hit, Recover, Ready",
    level: "foundation",
    purpose: "Return to a useful court position after every shot.",
    setup: "Place a home-base marker near the middle of your playing area.",
    steps: [
      "Move from home base to play the ball.",
      "Recover with small steps instead of turning your back to the net.",
      "Pause in ready position before the next feed.",
    ],
    socialTarget: "Complete 10 balanced hit-and-recover repetitions.",
    competitiveTarget: "Complete 12 randomized repetitions without being late or off balance.",
    solo: "Use shadow swings at two side markers and recover to home base.",
    partner: "Feed alternating forehand, backhand, and middle balls.",
  },
  {
    name: "Kitchen Shuffle",
    level: "foundation",
    purpose: "Improve lateral movement at the kitchen without crossing the feet or losing posture.",
    setup: "Place three markers along the kitchen line: left, middle, and right.",
    steps: [
      "Start in the middle in a ready position.",
      "Shuffle to the called marker while keeping the paddle in front.",
      "Return to the middle and reset before the next call.",
    ],
    socialTarget: "Complete 12 controlled movements without crossing your feet.",
    competitiveTarget: "Complete 18 random movements while staying balanced and ready.",
    solo: "Use a timer or shuffled direction cards.",
    partner: "A partner calls directions and occasionally adds a shadow volley cue.",
  },
  {
    name: "Transition Stop-Go",
    level: "developing",
    purpose: "Learn when to advance, stop, and split-step through the transition zone.",
    setup: "Begin at the baseline with markers at two transition-zone positions and the kitchen line.",
    steps: [
      "Advance toward the first marker after a simulated return.",
      "Stop and split-step on the feeder's contact cue.",
      "Continue only when the next ball allows safe movement forward.",
    ],
    socialTarget: "Reach the kitchen under control in 6 of 8 sequences.",
    competitiveTarget: "Reach the kitchen in 7 of 8 while staying balanced for every contact.",
    solo: "Use an audio timer with irregular beeps as contact cues.",
    partner: "A partner feeds controlled balls and varies the timing of each contact.",
    advancedVariation: "Add wide and body feeds that require recovery before continuing forward.",
  },
  {
    name: "Corner-to-Corner Recovery",
    level: "developing",
    purpose: "Improve first-step speed and recovery after being pulled wide.",
    setup: "Place wide markers near both sidelines and one recovery marker near the centre.",
    steps: [
      "Move to a wide marker and simulate a controlled shot.",
      "Recover with quick adjustment steps toward the centre marker.",
      "Split-step before moving to the next called side.",
    ],
    socialTarget: "Complete 10 repetitions while staying balanced.",
    competitiveTarget: "Complete 16 randomized repetitions without arriving late.",
    solo: "Alternate sides using a timer and shadow swings.",
    partner: "A partner points to the next target and varies the recovery time.",
    advancedVariation: "Add short-ball calls that require forward recovery instead of returning to centre.",
  },
  {
    name: "Read and React Footwork",
    level: "advanced",
    purpose: "Match movement direction and recovery choice to the opponent's contact and court position.",
    setup: "The player begins in a neutral ready position while a partner uses visual cues or live feeds.",
    steps: [
      "Read the feeder's paddle and body position before moving.",
      "Take an efficient first step rather than guessing early.",
      "Recover to the most useful position for the next likely ball.",
    ],
    socialTarget: "Choose the correct movement response on 8 of 12 cues.",
    competitiveTarget: "Choose correctly on 10 of 12 and arrive balanced for at least 9 contacts.",
    solo: "Use randomized video or card cues and rehearse the first two steps.",
    partner: "Use live, controlled feeds that vary direction, depth, and pace.",
    advancedVariation: "Play the rally live after the first feed and score both the movement decision and the shot outcome.",
  },
];
