import type { Drill } from "./drill-library";

export const consistencyDrills: Drill[] = [
  {
    name: "Ten-Ball Rally",
    level: "foundation",
    purpose: "Build repeatable control before increasing difficulty.",
    setup: "Choose one shot—dink, volley, or groundstroke—and agree on a comfortable pace.",
    steps: [
      "Count every successful contact aloud.",
      "Restart at zero after an error.",
      "After reaching ten, add placement or movement while keeping the same control.",
    ],
    socialTarget: "Complete 3 rallies of 10 controlled shots.",
    competitiveTarget: "Complete 3 rallies of 15, then play the final ball to a target.",
    solo: "Use a wall and mark a safe rebound zone.",
    partner: "Cooperate until the target is reached; do not try to win the rally.",
  },
  {
    name: "High-Percentage Choice",
    level: "foundation",
    purpose: "Practise choosing the safer ball when under pressure.",
    setup: "Play half-court points. Before contact, the hitter calls 'safe' or 'attack.'",
    steps: [
      "Choose 'safe' for balls below net height or when off balance.",
      "Choose 'attack' only when balanced with contact above net height.",
      "After each rally, review whether the choice—not only the result—was sound.",
    ],
    socialTarget: "Make an appropriate choice on 8 of 10 balls.",
    competitiveTarget: "Make an appropriate choice on 9 of 10 balls during scored half-court play.",
    solo: "Alternate low and high self-feeds and call the choice before swinging.",
    partner: "Vary feed height and give immediate choice feedback.",
  },
  {
    name: "Same Target, Same Shape",
    level: "foundation",
    purpose: "Develop a repeatable swing path and dependable target control.",
    setup: "Mark one generous target zone for a chosen shot.",
    steps: [
      "Hit ten balls using the same preparation and finish.",
      "Pause after each set of five to check balance and contact point.",
      "Increase pace only after maintaining target accuracy.",
    ],
    socialTarget: "Land 7 of 10 balls in the target zone.",
    competitiveTarget: "Land 9 of 12 while keeping no more than one unforced error per set.",
    solo: "Use a wall or drop feeds toward a marked target.",
    partner: "Provide repeatable feeds and note changes in swing shape or balance.",
  },
  {
    name: "Five-Ball Pattern",
    level: "developing",
    purpose: "Maintain control through a short sequence of different but connected shots.",
    setup: "Choose a five-shot pattern, such as deep return, third-shot drop, dink, dink, controlled attack.",
    steps: [
      "State the pattern before starting.",
      "Complete each shot with control rather than rushing to the next one.",
      "Restart after an error and identify where the pattern broke down.",
    ],
    socialTarget: "Complete the full pattern 4 times in 10 attempts.",
    competitiveTarget: "Complete it 6 times and win or neutralize the final exchange on at least 4.",
    solo: "Use wall targets or shadow movements for each stage of the sequence.",
    partner: "Feed or play the pattern cooperatively, then make the final ball live.",
    advancedVariation: "Use two possible patterns and choose between them based on the incoming ball.",
  },
  {
    name: "Error Budget",
    level: "developing",
    purpose: "Build rally discipline by managing a limited number of unforced errors.",
    setup: "Play cooperative or scored half-court rallies with an error allowance of three.",
    steps: [
      "Begin with three available error tokens.",
      "Remove one token after each unforced error.",
      "Reset the count only after reaching the rally or point target.",
    ],
    socialTarget: "Complete 3 rallies of 12 before using all three tokens.",
    competitiveTarget: "Win a race to 7 points while committing no more than three unforced errors.",
    solo: "Use a wall rally and track misses against a three-error allowance.",
    partner: "Play half-court and classify errors together after each rally.",
    advancedVariation: "Reduce the allowance to two and add a required target on the final ball.",
  },
  {
    name: "Pressure Repeat",
    level: "advanced",
    purpose: "Reproduce a successful shot or pattern when the score creates pressure.",
    setup: "Choose one reliable shot or pattern and begin each repetition at a simulated late-game score.",
    steps: [
      "Announce the score before starting.",
      "Use the same routine and target on every repetition.",
      "After a miss, repeat immediately without changing mechanics or forcing more pace.",
    ],
    socialTarget: "Complete 6 of 10 repetitions with the intended shape and target.",
    competitiveTarget: "Complete 8 of 10 and succeed on the final two pressure repetitions.",
    solo: "Use target zones and alternate simulated scores such as 8-8, 9-9, and 10-10.",
    partner: "Play the selected sequence live and vary only the final defensive response.",
    advancedVariation: "Require two consecutive successful repetitions before advancing to a harder target.",
  },
];
