import type { Drill } from "./drill-library";

export const defenseDrills: Drill[] = [
  {
    name: "Reset and Breathe",
    level: "foundation",
    purpose: "Soften a hard ball into the kitchen and regain control.",
    setup: "The defender begins in the transition zone while a feeder stands at the kitchen line.",
    steps: [
      "Use a compact block with a relaxed grip.",
      "Aim for the middle of the kitchen.",
      "Hold your balance after contact before moving forward.",
    ],
    socialTarget: "Land 6 of 10 resets in the kitchen.",
    competitiveTarget: "Land 7 of 10 resets in the kitchen from randomized feeds.",
    solo: "Against a wall, absorb firm rebounds so the next bounce lands close to you.",
    partner: "The feeder increases pace only after three successful resets.",
  },
  {
    name: "Two-Step Recovery",
    level: "foundation",
    purpose: "Defend, regain balance, and move forward only when the ball permits.",
    setup: "Begin one step behind the kitchen while a partner applies controlled pressure.",
    steps: [
      "Block the first ball softly.",
      "Recover the paddle and feet before taking a small step forward.",
      "Repeat until you safely reach the kitchen line.",
    ],
    socialTarget: "Reach the kitchen under control in 5 of 8 sequences.",
    competitiveTarget: "Reach the kitchen and neutralize 6 of 8 randomized sequences.",
    solo: "Shadow block, recover, and step movements using a wall rebound or imaginary feed.",
    partner: "The feeder varies forehand and backhand pressure while keeping the drill safe.",
  },
  {
    name: "Middle Reset Window",
    level: "foundation",
    purpose: "Use a high-percentage reset target that reduces sharp angles for the opponent.",
    setup: "Mark a wide target in the middle third of the kitchen.",
    steps: [
      "Receive ten firm feeds from the transition zone.",
      "Relax the grip and guide the ball into the middle target.",
      "Recover to ready position before the next feed.",
    ],
    socialTarget: "Land 7 of 10 resets in the middle kitchen target.",
    competitiveTarget: "Land 8 of 10 and prevent an immediate attack on at least 6.",
    solo: "Use a wall target that rewards soft rebounds landing near your feet.",
    partner: "The feeder changes pace slightly while keeping the ball within reach.",
  },
  {
    name: "Block and Counter",
    level: "developing",
    purpose: "Choose between absorbing pace and counterattacking based on ball height and balance.",
    setup: "Both players begin at the kitchen. The feeder alternates attacks at different heights.",
    steps: [
      "Call 'block' for balls at or below comfortable paddle height.",
      "Call 'counter' for balls that arrive high enough while you are balanced.",
      "Return the paddle to ready position after every contact.",
    ],
    socialTarget: "Make the appropriate choice on 8 of 12 feeds.",
    competitiveTarget: "Choose correctly on 10 of 12 and control 8 responses.",
    solo: "Alternate low and high wall feeds and call the choice before contact.",
    partner: "The feeder randomizes height and direction without announcing the feed.",
    advancedVariation: "Play the rally live after the first defensive contact and score the quality of the decision, not just the outcome.",
  },
  {
    name: "Transition Zone Survival",
    level: "developing",
    purpose: "Stay composed through multiple defensive balls while advancing safely.",
    setup: "The defender begins midway between the baseline and kitchen. The feeder starts at the kitchen.",
    steps: [
      "Defend the first ball without forcing forward movement.",
      "Advance only after a reset that lands safely in the kitchen.",
      "Repeat until the defender reaches the kitchen or loses control.",
    ],
    socialTarget: "Reach the kitchen in 5 of 8 sequences.",
    competitiveTarget: "Reach the kitchen in 6 of 8 while allowing no more than one attackable reset per sequence.",
    solo: "Use wall rebounds to practise block, recover, and controlled forward steps.",
    partner: "The feeder varies speed and direction while keeping the sequence playable.",
    advancedVariation: "Add occasional lobs or wide feeds to test recovery without rushing.",
  },
  {
    name: "Defend the Pattern",
    level: "advanced",
    purpose: "Recognize attacking patterns and choose the safest defensive response under pressure.",
    setup: "The attacker uses one of three patterns: body attack, wide attack, or attack followed by open-space finish.",
    steps: [
      "Read the attacker's preparation and protect the most likely target.",
      "Use a block, reset, or counter based on height and balance.",
      "Recover immediately for the next ball in the pattern.",
    ],
    socialTarget: "Neutralize 5 of 10 attacking patterns.",
    competitiveTarget: "Neutralize 7 of 10 and regain a neutral kitchen rally on at least 5.",
    solo: "Use shuffled pattern cards and rehearse the first two defensive movements.",
    partner: "The attacker selects patterns randomly and plays the rally through completion.",
    advancedVariation: "Hide the attacker's chosen pattern until the rally begins and award bonus points for correct anticipation plus controlled execution.",
  },
];
