import type { Drill } from "./drill-library";

export const offenseDrills: Drill[] = [
  {
    name: "Green-Light Attack",
    level: "foundation",
    purpose: "Recognize attackable balls and stay patient on lower balls.",
    setup: "Both players begin at the kitchen. The feeder alternates neutral dinks and slightly elevated balls.",
    steps: [
      "Call 'wait' for a neutral ball and continue dinking.",
      "Call 'go' for an attackable ball and speed it up with a compact swing.",
      "Recover the paddle to ready position immediately.",
    ],
    socialTarget: "Correctly identify 8 of 10 attackable or neutral balls.",
    competitiveTarget: "Correctly identify 9 of 10 and place 7 attacks below shoulder height.",
    solo: "Use alternating low and higher self-feeds against a wall; attack only the higher rebound.",
    partner: "The feeder randomizes height without telling the hitter what is coming.",
    advancedVariation: "Mix in low feeds and use a disguised topspin flick only when balance and contact allow it.",
  },
  {
    name: "Finish to Space",
    level: "foundation",
    purpose: "Replace hitting harder with purposeful placement into open court.",
    setup: "Place two targets near an opponent's feet or in open space. Begin with a cooperative kitchen exchange.",
    steps: [
      "Wait for a ball above net height.",
      "Choose the open target before contact.",
      "Use a compact swing and recover for the next ball.",
    ],
    socialTarget: "Hit 6 of 10 controlled attacks into either target zone.",
    competitiveTarget: "Hit 7 of 10 into the called target while the defender moves naturally.",
    solo: "Mark two wall targets and alternate placement after a controlled self-feed.",
    partner: "The defender awards a point for placement rather than raw speed.",
  },
  {
    name: "Attack the Feet",
    level: "foundation",
    purpose: "Develop a safe offensive target that forces difficult defensive contact.",
    setup: "A defender stands at the kitchen while the hitter receives slightly elevated feeds from the opposite side.",
    steps: [
      "Choose the defender's paddle-side or outside foot before swinging.",
      "Keep the contact compact and below maximum pace.",
      "Recover to ready position and expect the ball to come back.",
    ],
    socialTarget: "Direct 7 of 12 attacks below knee height.",
    competitiveTarget: "Direct 9 of 12 below knee height and win or control 7 follow-up balls.",
    solo: "Place low wall targets and hit from controlled self-feeds.",
    partner: "The defender blocks the ball back so the hitter practises the next shot.",
  },
  {
    name: "Third-Shot Drop or Drive",
    level: "developing",
    purpose: "Choose between a drop and a drive based on ball height, balance, and court position.",
    setup: "The hitter begins at the baseline. A partner feeds returns of different depth and height.",
    steps: [
      "Call 'drop' or 'drive' before contact.",
      "Use a drop when the ball is low or balance is limited.",
      "Use a drive when contact is comfortable and the target is available.",
    ],
    socialTarget: "Make an appropriate choice on 8 of 12 feeds and land 7 playable third shots.",
    competitiveTarget: "Choose correctly on 10 of 12 and earn a neutral or attacking fifth shot on 8.",
    solo: "Alternate low and higher self-feeds and call the choice before hitting.",
    partner: "The feeder varies depth and plays out the fifth shot after each third.",
    advancedVariation: "Disguise both choices with similar preparation and play the point through the fifth shot.",
  },
  {
    name: "Speed-Up Plus One",
    level: "developing",
    purpose: "Connect a controlled speed-up with readiness for the expected counterattack.",
    setup: "Both players begin at the kitchen and dink cooperatively until the attacker receives a suitable ball.",
    steps: [
      "Speed up to a planned target using a compact motion.",
      "Return the paddle immediately to the centre ready position.",
      "Control the next ball rather than admiring the attack.",
    ],
    socialTarget: "Complete 6 of 10 speed-up-and-next-ball sequences under control.",
    competitiveTarget: "Win or gain a clear advantage on 7 of 10 sequences.",
    solo: "Use a wall sequence of soft feed, controlled attack, then quick ready-position block.",
    partner: "The defender counters naturally after every speed-up.",
    advancedVariation: "Alternate body, backhand shoulder, and open-space targets without changing preparation.",
  },
  {
    name: "Pattern the Point",
    level: "advanced",
    purpose: "Use a deliberate two- or three-shot pattern instead of attacking without a plan.",
    setup: "Choose one pattern, such as wide dink, middle speed-up, then finish to open space.",
    steps: [
      "State the intended pattern before the rally.",
      "Build the first shot patiently rather than forcing it.",
      "Attack only when the planned opening appears, then recover for the next ball.",
    ],
    socialTarget: "Complete the intended pattern 4 times in 10 rallies.",
    competitiveTarget: "Complete it 6 times and win at least 5 of those rallies.",
    solo: "Use three wall targets and move through the sequence in order.",
    partner: "The defender plays live while allowing the attacker to recognize whether the pattern remains appropriate.",
    advancedVariation: "Prepare two different patterns and choose between them based on the opponent's movement.",
  },
];
